name: dishtv_agent_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.2+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  equatable: ^2.0.5
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  intl: ^0.19.0
  fl_chart: ^0.68.0
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  permission_handler: ^11.3.1
  open_file: ^3.3.2
  device_info_plus: ^10.1.0
  pdf: ^3.10.8 # Add this line for PDF generation
  share_plus: ^9.0.0
  shimmer: ^3.0.0
  percent_indicator: ^4.2.3 # <-- यह नया पैकेज जोड़ा गया है

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0 # <-- यह लाइन जोड़ें
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

# यह नया और बेहतर कॉन्फ़िगरेशन है
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png" # यह सामान्य आइकन के लिए है
  min_sdk_android: 21
  remove_alpha_ios: true
  # Android के नए वर्ज़न के लिए ये सेटिंग्स ज़रूरी हैं
  adaptive_icon_background: "#1E1E1E" # बैकग्राउंड का रंग (आप इसे बदल सकते हैं)
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png" # फोरग्राउंड के लिए नई इमेज

# यह नया सेक्शन सबसे नीचे जोड़ा गया है
flutter_native_splash:
  color: "#1E1E1E" # डार्क मोड बैकग्राउंड कलर
  color_dark: "#1E1E1E"
  image: assets/icon/app_icon.png
  image_dark: assets/icon/app_icon.png
  android_12:
    image: assets/icon/app_icon.png
    icon_background_color: "#1E1E1E"